server:
  port: 8282

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlinebookstore
    username: onlinebookstore
    password: onlinebookstore
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

